// 单一来源的 Release Note（v1.1.0），被 release.js 与 gen-update-json.cjs 共用，
// 确保 Gitee Release body 与 update-windows-x86_64.json 的 notes 完全一致。
const VERSION = '1.1.0';

const notesLines = [
  '## ⬇️ 下载',
  '',
  '> **🏆 推荐大多数用户选择：** [⬇ TizuMark_' + VERSION + '_x64-setup.exe](https://gitee.com/tizu/tizu-mark/releases/download/v' + VERSION + '/TizuMark_' + VERSION + '_x64-setup.exe)',
  '>',
  '> **🛠 企业/批量部署：** [⬇ TizuMark_' + VERSION + '_x64_en-US.msi](https://gitee.com/tizu/tizu-mark/releases/download/v' + VERSION + '/TizuMark_' + VERSION + '_x64_en-US.msi)',
  '>',
  '> **📦 绿色版（免安装）：** [⬇ TizuMark_' + VERSION + '_x64.exe](https://gitee.com/tizu/tizu-mark/releases/download/v' + VERSION + '/TizuMark_' + VERSION + '_x64.exe)',
  '',
  '### 三种安装包说明',
  '',
  '| 安装包 | 适用人群 | 特点 |',
  '|--------|---------|------|',
  '| ⭐ **NSIS 安装包 (.exe)** — **推荐** | 绝大多数 Windows 用户 | 传统的 setup 向导安装，支持自定义安装路径、创建桌面快捷方式、自动注册文件关联。双击即装，即装即用。 |',
  '| **MSI 安装包 (.msi)** | 企业 IT 管理员、需要批量部署的用户 | 标准的 Windows Installer 格式，支持组策略推送、静默安装（msiexec /i TizuMark_' + VERSION + '_x64_en-US.msi /qn）、适合企业环境集中管理。 |',
  '| **绿色版 (.exe)** | 追求便携的用户 | 单文件免安装，解压即用，适合 U 盘携带、临时使用，不写注册表。 |',
  '',
  '---',
  '',
  '## ✨ v' + VERSION + ' 更新内容',
  '',
  '### 新增',
  '- 脚注（footnote）支持，可双向跳转',
  '- 段落内换行（单个换行即渲染为换行，符合书写直觉）',
  '- 关闭窗口行为偏好（询问／退出／最小化到系统托盘）+ 托盘图标显隐设置',
  '- 窗口位置与大小记忆，重启自动恢复',
  '- 「重新加载文件」与「开发者工具」入口',
  '- 最近打开文件列表',
  '- 标签页拖拽排序、中键关闭标签',
  '- 引用块内任务列表',
  '- 快捷键方案预设下拉（默认／VS Code／Typora／Sublime 等）',
  '- 跨文件搜索增强（结果点击跳转、正则＋目录搜索、性能提升）',
  '- 预览放开内联 style（HTML 卡片等可正常渲染，带安全过滤）',
  '- 支持 GitHub 风格行内数学（反引号定界）',
  '- 首次启动／升级后自动打开使用说明与完整示例 demo.md',
  '- 表格行尾回车自动补全等列空行，空行回车退出表格',
  '',
  '### 改进',
  '- 任务列表勾选即时生效并恢复点击响应',
  '- 编辑／预览滚动同步精度提升（切换标签、加载文件时恢复双栏位置）',
  '- 软换行开关修复并生效',
  '- 预览锚点跳转与外部 .md 链接修复',
  '- 大文档预览渲染缓存（Mermaid／图片），切换更流畅',
  '- 代码块行号／自动换行可配置',
  '- 提示框（Callout）支持自定义标题',
  '- 移除误打包的冗余资源，安装包体积更小',
  '',
  '### 修复',
  '- 修复任务列表勾选点击无响应',
  '- 修复跨文件搜索点击结果不跳转',
  '- 修复外部 .md 链接与预览锚点跳转',
  '- 修复软换行开关失效',
  '- 修复切换代码行号后代码块出现多余 []',
  '- 修复不成对行内数学定界符跨段配对吞掉正文',
  '- 修复自定义字体不生效与恢复默认误删字体',
  '- 安全：预览渲染增加安全过滤（内联 style 白名单校验），升级相关依赖',
  '',
  '> 使用中遇到问题欢迎加 QQ 群：1035294939',
];

module.exports = { VERSION, notesLines };
